"""Merge all data sources into a single DataFrame.

Reads pre-collected data from data/ files (generated by collect_data.py).
"""

from pathlib import Path

import pandas as pd
from src.config import COMPETITORS
from src.static_metadata import COMPETITOR_METADATA

DATA_DIR = Path(__file__).parent.parent / "data"


def _load_json(filename: str) -> pd.DataFrame:
    """Load a JSON data file, return empty DataFrame if missing."""
    path = DATA_DIR / filename
    if not path.exists():
        return pd.DataFrame()
    return pd.read_json(path)


def _load_csv(filename: str) -> pd.DataFrame:
    """Load a CSV data file, return empty DataFrame if missing."""
    path = DATA_DIR / filename
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


def aggregate_all() -> tuple[pd.DataFrame, list[str]]:
    """Build the full competitor DataFrame from static files.

    Returns:
        (df, warnings) — DataFrame with all data, list of warning messages.
    """
    warnings = []

    # 1. Base registry
    df = pd.DataFrame(COMPETITORS)

    # 2. Static metadata
    meta_rows = []
    for name, meta in COMPETITOR_METADATA.items():
        row = {"name": name}
        for k, v in meta.items():
            if k in ("strengths", "weaknesses"):
                continue  # Keep these in the dict, not flat columns
            row[k] = v
        meta_rows.append(row)
    meta_df = pd.DataFrame(meta_rows)
    df = df.merge(meta_df, on="name", how="left")

    # 3. DeFi Llama TVL
    defillama_df = _load_json("defillama.json")
    if defillama_df.empty:
        warnings.append("DeFi Llama: No data file (run collect_data.py)")
    else:
        df = df.merge(defillama_df, on="defillama_slug", how="left")

    # 3b. CoinGecko market cap (for tokens DeFi Llama doesn't track)
    coingecko_df = _load_json("coingecko.json")
    if not coingecko_df.empty:
        df = df.merge(coingecko_df, on="name", how="left")

    # 4. DeFi yields
    yields_df = _load_json("defi_yields.json")
    if yields_df.empty:
        warnings.append("DeFi Yields: No data file (run collect_data.py)")
    else:
        df = df.merge(yields_df, on="name", how="left")

    # 5. The Graph (Aave)
    graph_df = _load_csv("thegraph.csv")
    if graph_df.empty:
        warnings.append("The Graph: No data file (run collect_data.py)")
    else:
        df = df.merge(graph_df, on="aave_symbol", how="left")

    # 6. Dune Analytics
    dune_df = _load_csv("dune.csv")
    if dune_df.empty:
        warnings.append("Dune: No data file (run collect_data.py)")
    else:
        # Normalize addresses for join
        if "dune_token_address" in df.columns and "dune_token_address" in dune_df.columns:
            df["_dune_join"] = df["dune_token_address"].str.lower()
            dune_df["_dune_join"] = dune_df["dune_token_address"].str.lower()
            dune_cols = [c for c in dune_df.columns if c != "dune_token_address"]
            df = df.merge(dune_df[dune_cols], on="_dune_join", how="left")
            df.drop(columns=["_dune_join"], inplace=True, errors="ignore")

    # 7. Derived columns
    # effective_tvl: DeFi Llama TVL > CoinGecko market cap > manual_aum
    if "tvl_usd" not in df.columns:
        df["tvl_usd"] = None
    if "coingecko_mcap" not in df.columns:
        df["coingecko_mcap"] = None
    if "manual_aum" not in df.columns:
        df["manual_aum"] = None

    df["effective_tvl"] = df["tvl_usd"].fillna(df["coingecko_mcap"]).fillna(df["manual_aum"])

    def _tvl_source(r):
        if pd.notna(r.get("tvl_usd")):
            return "defillama"
        if pd.notna(r.get("coingecko_mcap")):
            return "coingecko"
        if pd.notna(r.get("manual_aum")):
            return "manual"
        return None

    df["tvl_source"] = df.apply(_tvl_source, axis=1)

    # Ensure numeric columns exist
    for col in ["holders_count", "daily_active_addresses_avg", "bridge_volume_30d_usd",
                "defi_integrations_count", "total_pool_tvl"]:
        if col not in df.columns:
            df[col] = None

    # Composite adoption score (normalized 0-1)
    def _normalize(series):
        s = pd.to_numeric(series, errors="coerce")
        s_min, s_max = s.min(), s.max()
        if s_max and s_max > s_min:
            return (s - s_min) / (s_max - s_min)
        return s.fillna(0) * 0

    df["composite_adoption_score"] = (
        _normalize(df["holders_count"]) * 0.5 +
        _normalize(df["effective_tvl"]) * 0.3 +
        _normalize(df["daily_active_addresses_avg"]) * 0.2
    )

    return df, warnings


def get_strengths_weaknesses() -> dict:
    """Return the raw strengths/weaknesses dicts from metadata."""
    result = {}
    for name, meta in COMPETITOR_METADATA.items():
        result[name] = {
            "strengths": meta.get("strengths", {}),
            "weaknesses": meta.get("weaknesses", {}),
        }
    return result
