"""Pre-baked qualitative data for all competitors. Zero manual work at runtime.

Every numeric claim has a `sources` dict documenting where the data came from.
Fields marked with `_source` indicate the origin of the corresponding value.
Last verified: March 2026.
"""

COMPETITOR_METADATA = {
    # ===== Cluster 1: CeFi =====
    "Nexo": {
        "custody_type": "custodial", "kyc": True, "self_custodial": False,
        "ltv_max": 0.50, "apr_range": "0%–18.9% (by loyalty tier)",
        "description": "CeFi wealth platform, ~$3B BTC exposure (est.), $11B+ total platform AUM, 2nd largest centralized crypto lender",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "CeFi incumbents retain conservative BTC holders who won't try DeFi",
        "manual_aum": 3_000_000_000, "funding": "Series A (undisclosed)", "audit_status": "audited",
        "strengths": {"btc_holder": "Easy UX, instant loans, regulated", "custodian": "Established compliance", "defi_protocol": "N/A — centralized"},
        "weaknesses": {"btc_holder": "Custodial risk, KYC, counterparty exposure", "custodian": "Competes with own custody", "defi_protocol": "No composability"},
        "sources": {
            "manual_aum": "Nexo reports $11B+ total platform AUM (all crypto). BTC-only exposure estimated ~$3B (midpoint of $2-4B range; asset breakdown not publicly disclosed)",
            "apr_range": "Nexo website (Mar 2026): 0% (Platinum, LTV<=20%) to 18.9% (Base tier)",
            "ltv_max": "Nexo product page: up to 50% LTV",
        },
    },
    "Ledn": {
        "custody_type": "custodial", "kyc": True, "self_custodial": False,
        "ltv_max": 0.50, "apr_range": "~12%",
        "description": "Largest retail BTC lender. $9.5B+ originated (cumulative), $100M+ ARR (Q3 2025), Tether investor, PoR",
        "threat_level": "medium", "momentum": "growing",
        "key_risk_to_babylon": "Largest retail lender; BTC holders may choose simplicity over self-custody",
        "manual_aum": 836_000_000, "funding": "$70M Series B (10T Holdings)", "audit_status": "audited",
        "strengths": {"btc_holder": "No credit check, fast funding, transparent PoR, BTC-only", "custodian": "Survived 2022 crisis, strong risk mgmt", "defi_protocol": "N/A — centralized"},
        "weaknesses": {"btc_holder": "Custodial, KYC, jurisdiction limits", "custodian": "Centralized model limits scale", "defi_protocol": "No composability"},
        "sources": {
            "manual_aum": "Ledn Q3 2025: loan book $836.2M (Sep 30, 2025)",
            "description": "The Block (Oct 2025): $9.5B+ cumulative originated, $100M+ ARR; Tether strategic investment (Nov 2025)",
            "funding": "PR Newswire (Dec 2021): $70M Series B led by 10T Holdings",
            "ltv_max": "Ledn website: up to 50% LTV; avg portfolio LTV 42.68% (Q3 2025)",
        },
    },
    "Xapo Bank": {
        "custody_type": "custodial", "kyc": True, "self_custodial": False,
        "ltv_max": 0.40, "apr_range": "Unknown",
        "description": "Licensed bank (Gibraltar), BTC-backed credit lines",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "Banking license offers regulatory comfort TBV lacks",
        "manual_aum": None, "funding": "Acquired by Coinbase alumni", "audit_status": "audited",
        "strengths": {"btc_holder": "Banking license, deposit protection", "custodian": "Regulated bank", "defi_protocol": "N/A"},
        "weaknesses": {"btc_holder": "Low LTV, limited access", "custodian": "N/A", "defi_protocol": "N/A"},
        "sources": {},
    },
    "Lygos Finance": {
        "custody_type": "custodial", "kyc": True, "self_custodial": False,
        "ltv_max": None, "apr_range": "Unknown",
        "description": "Institutional BTC lending",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "Institutional niche overlap",
        "manual_aum": None, "funding": "Undisclosed", "audit_status": "unaudited",
        "strengths": {"btc_holder": "Institutional grade", "custodian": "Enterprise-focused", "defi_protocol": "N/A"},
        "weaknesses": {"btc_holder": "Not retail, custodial", "custodian": "Niche", "defi_protocol": "N/A"},
        "sources": {},
    },
    "Two Prime": {
        "custody_type": "custodial", "kyc": True, "self_custodial": False,
        "ltv_max": None, "apr_range": "Unknown",
        "description": "Institutional digital asset fund",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "Minimal overlap — institutional fund, not infra",
        "manual_aum": None, "funding": "Undisclosed", "audit_status": "unaudited",
        "strengths": {"btc_holder": "Institutional infra", "custodian": "Fund-level risk mgmt", "defi_protocol": "N/A"},
        "weaknesses": {"btc_holder": "Not retail, custodial", "custodian": "N/A", "defi_protocol": "N/A"},
        "sources": {},
    },
    "Bitcoin Suisse": {
        "custody_type": "custodial", "kyc": True, "self_custodial": False,
        "ltv_max": None, "apr_range": "Unknown",
        "description": "Swiss-regulated crypto financial services",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "Swiss regulation as competitive moat for EU market",
        "manual_aum": None, "funding": "Undisclosed", "audit_status": "audited",
        "strengths": {"btc_holder": "Swiss regulation, brand", "custodian": "Strong compliance", "defi_protocol": "N/A"},
        "weaknesses": {"btc_holder": "High barriers, custodial", "custodian": "Jurisdiction-limited", "defi_protocol": "N/A"},
        "sources": {},
    },
    "SatsTerminal": {
        "custody_type": "non-custodial", "kyc": False, "self_custodial": True,
        "ltv_max": None, "apr_range": "Unknown",
        "description": "BTC-native non-custodial lending. Borrow product live Jan 2026. Gate Ventures strategic investment Mar 2026",
        "threat_level": "medium", "momentum": "growing",
        "key_risk_to_babylon": "Non-custodial BTC lending is closest CeFi analog to TBV value prop",
        "manual_aum": None, "funding": "$1.7M pre-seed (Coinbase Ventures, Draper Associates, Yzi Labs)", "audit_status": "unaudited",
        "strengths": {"btc_holder": "Non-custodial, no KYC, native BTC, cross-chain", "custodian": "No custody needed", "defi_protocol": "Cross-chain composability"},
        "weaknesses": {"btc_holder": "Early stage, unproven", "custodian": "New integration model", "defi_protocol": "Small TVL"},
        "sources": {
            "funding": "The Block (Apr 2025): $1.7M pre-seed led by Coinbase Ventures & Draper Associates; Gate Ventures strategic investment (Mar 4, 2026)",
        },
    },

    # ===== Cluster 2: Centralized Wrapped BTC =====
    "wBTC": {
        "custody_type": "custodial", "kyc": False, "self_custodial": False,
        "ltv_max": 0.73, "apr_range": "Variable (Aave ~2-5%)",
        "description": "Largest wrapped BTC. BitGo custody. mcap from DeFi Llama API",
        "threat_level": "high", "momentum": "stable",
        "key_risk_to_babylon": "Deep liquidity moat; DeFi protocols default to wBTC collateral",
        "funding": "N/A (BitGo)", "audit_status": "audited",
        "strengths": {"btc_holder": "Deepest liquidity, accepted everywhere, 1:1 redeemable", "custodian": "Standardized ERC-20", "defi_protocol": "Most liquid BTC collateral, proven"},
        "weaknesses": {"btc_holder": "Centralized custody (BitGo), peg risk", "custodian": "BitGo dependency", "defi_protocol": "Single point of failure"},
        "sources": {
            "ltv_max": "Aave V3 on-chain: baseLTVasCollateral = 73%",
        },
    },
    "cbBTC": {
        "custody_type": "custodial", "kyc": False, "self_custodial": False,
        "ltv_max": 0.73, "apr_range": "Variable (Aave)",
        "description": "Coinbase wrapped BTC. $6.2B market cap, 88.8K cbBTC in circulation (ETH/Base/Solana/Arb). CCIP bridge to Monad (Mar 2026)",
        "threat_level": "high", "momentum": "growing",
        "key_risk_to_babylon": "Coinbase distribution + institutional trust; Monad bridge shows aggressive expansion",
        "manual_aum": 6_200_000_000,
        "funding": "N/A (Coinbase)", "audit_status": "audited",
        "strengths": {"btc_holder": "Regulated custodian, institutional trust, PoR", "custodian": "Coinbase compliance", "defi_protocol": "Growing integrations"},
        "weaknesses": {"btc_holder": "Coinbase SPOF, US regulatory risk", "custodian": "Concentrated", "defi_protocol": "Less liquid than wBTC"},
        "sources": {
            "manual_aum": "CoinGecko (Mar 2026): $6.2B market cap, 88,785 cbBTC circulating. Not tracked as protocol on DeFi Llama.",
            "description": "Chainlink CCIP bridge to Monad announced Mar 2, 2026",
            "ltv_max": "Aave V3 on-chain: baseLTVasCollateral = 73%",
        },
    },

    # ===== Cluster 3: Trust-Minimized =====
    "tBTC": {
        "custody_type": "federated-multisig", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Variable",
        "description": "Threshold Network. Oldest trust-minimized BTC bridge",
        "threat_level": "medium", "momentum": "stable",
        "key_risk_to_babylon": "Oldest trust-minimized bridge; growing Aave integration",
        "funding": "Threshold DAO treasury", "audit_status": "audited",
        "strengths": {"btc_holder": "No KYC, decentralized custody, battle-tested", "custodian": "No single custodian", "defi_protocol": "Trust-minimized, Aave/Curve growing"},
        "weaknesses": {"btc_holder": "Lower liquidity, federation trust", "custodian": "Threshold trust", "defi_protocol": "Smaller pools"},
        "sources": {},
    },
    "LBTC": {
        "custody_type": "trust-minimized", "kyc": False, "self_custodial": False,
        "ltv_max": 0.84, "apr_range": "Staking yield + DeFi",
        "description": "Lombard. ~$2B in circulation, 70+ protocol integrations. 70% of supply active in DeFi (Aave, Morpho). Multichain: ETH, Sui, Solana, Starknet",
        "threat_level": "high", "momentum": "growing",
        "key_risk_to_babylon": "Strongest direct competitor: 70+ integrations, 84% LTV, rapid multichain expansion. Babylon dependency means they co-opt TBV narrative",
        "funding": "$16M seed (Polychain Capital, Jul 2024)", "audit_status": "audited",
        "strengths": {"btc_holder": "Staking yield + DeFi, 84% LTV, 70+ integrations", "custodian": "CubeSigner non-custodial keys", "defi_protocol": "High composability, blue-chip protocols"},
        "weaknesses": {"btc_holder": "Not truly self-custodial (security consortium)", "custodian": "Babylon dependency", "defi_protocol": "Concentrated in Aave"},
        "sources": {
            "description": "Lombard blog & The Block (2025-2026): ~$2B supply, 70+ integrations; Ledger integration Jan 2026; Sui & Solana launches",
            "funding": "The Block (Jul 2024): $16M seed led by Polychain Capital",
            "ltv_max": "Lombard product spec: up to 84% LTV. Note: Aave V3 on-chain LTV for LBTC = 70%",
        },
    },
    "SolvBTC": {
        "custody_type": "trust-minimized", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Variable yield",
        "description": "~$2.15B TVL, 1.2M users, 11 chains, 325 projects integrated. Chainlink CCT, BTC+ Vault",
        "threat_level": "high", "momentum": "growing",
        "key_risk_to_babylon": "Multichain presence + $2B+ TVL could fragment BTC DeFi before TBV launches",
        "funding": "$25M+ total (multiple rounds)", "audit_status": "partial",
        "strengths": {"btc_holder": "Multichain, yield strategies, institutional vault", "custodian": "Chainlink PoR + CCT", "defi_protocol": "Wide multichain, Chainlink stack"},
        "weaknesses": {"btc_holder": "Basket structure, not single-BTC", "custodian": "Multiple bridge surfaces", "defi_protocol": "Fragmented liquidity"},
        "sources": {
            "description": "DeFi Llama & KuCoin Learn (May 2025): $2.15B TVL, 19,456 BTC; Solv website: 1.2M users, 11 chains, 325 projects",
            "funding": "Bitcoin.com News (2025): $25M total raised; CryptoRank: 9 rounds, 33 investors",
        },
    },
    "FBTC": {
        "custody_type": "custodial", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Variable",
        "description": "Ignition/Mantle ecosystem wrapped BTC",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "Ecosystem-locked to Mantle — minimal overlap",
        "funding": "Ignition/Mantle backed", "audit_status": "partial",
        "strengths": {"btc_holder": "Mantle access", "custodian": "Ecosystem-native", "defi_protocol": "Mantle DeFi"},
        "weaknesses": {"btc_holder": "Ecosystem-locked", "custodian": "Niche", "defi_protocol": "Limited cross-chain"},
        "sources": {},
    },
    "uniBTC": {
        "custody_type": "trust-minimized", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Variable",
        "description": "Bedrock. Proxy/conversion staking to Babylon. TVL from DeFi Llama API",
        "threat_level": "medium", "momentum": "stable",
        "key_risk_to_babylon": "Proxy Babylon staking dilutes TBV differentiation",
        "funding": "OKX Ventures", "audit_status": "partial",
        "strengths": {"btc_holder": "Babylon exposure, flexible staking", "custodian": "OKX Ventures backed", "defi_protocol": "Multi-asset staking"},
        "weaknesses": {"btc_holder": "Proxy staking intermediary risk", "custodian": "Third-party staking", "defi_protocol": "Smaller scale"},
        "sources": {},
    },
    "eBTC": {
        "custody_type": "trustless", "kyc": False, "self_custodial": True,
        "ltv_max": None, "apr_range": "CDP model",
        "description": "BadgerDAO CDP. Synthetic BTC against stETH",
        "threat_level": "low", "momentum": "declining",
        "key_risk_to_babylon": "Synthetic model, different market segment",
        "funding": "BadgerDAO treasury", "audit_status": "audited",
        "strengths": {"btc_holder": "Trustless CDP, no intermediary", "custodian": "No custodian", "defi_protocol": "Immutable contracts"},
        "weaknesses": {"btc_holder": "Synthetic — not real BTC", "custodian": "N/A", "defi_protocol": "Small TVL, niche"},
        "sources": {},
    },
    "pumpBTC": {
        "custody_type": "semi-custodial", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Staking yield",
        "description": "Babylon LST. $500M+ TVL (Apr 2025), 3rd largest Babylon finality provider. Custodians: Cobo, Coincover. PUMP token Apr 2025",
        "threat_level": "medium", "momentum": "growing",
        "key_risk_to_babylon": "Direct Babylon LST competitor; custodial but simpler UX",
        "funding": "Undisclosed", "audit_status": "partial",
        "strengths": {"btc_holder": "Simple Babylon staking, points, PUMP token", "custodian": "Professional custodians", "defi_protocol": "Babylon ecosystem"},
        "weaknesses": {"btc_holder": "Third-party custody", "custodian": "Custodian concentration", "defi_protocol": "Smaller scale"},
        "sources": {
            "description": "BingX Academy / Messari Q1 2025: $500M+ TVL, 5,957 BTC end Q1 2025; 3rd largest Babylon LST by TVL",
        },
    },
    "sBTC": {
        "custody_type": "federated-multisig", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "STX staking rewards",
        "description": "Stacks L2. ~$545M TVL, 7,400+ holders. 15 community-elected signers -> permissionless. Fireblocks (Feb 2026)",
        "threat_level": "high", "momentum": "growing",
        "key_risk_to_babylon": "Bitcoin finality + $545M TVL + Fireblocks institutional backing is strong narrative",
        "funding": "$165M+ via Stacks ecosystem", "audit_status": "audited",
        "strengths": {"btc_holder": "100% Bitcoin finality, BitGo + Fireblocks, no KYC", "custodian": "Institutional via Fireblocks (Feb 2026)", "defi_protocol": "Stacks DeFi, Wormhole multichain to Sui (early 2026)"},
        "weaknesses": {"btc_holder": "15 signers (not fully decentralized)", "custodian": "Signer rotation complexity", "defi_protocol": "Clarity limits dev ecosystem"},
        "sources": {
            "description": "Stacks.co / CoinMarketCap (2025-2026): ~$545M TVL, 7,400+ holders, 62 BTC rewards. 15 signers (corrected from 14). Fireblocks integration Feb 4, 2026",
            "funding": "Unverified aggregate — Stacks ecosystem total, not a single round",
        },
    },
    "Lorenzo stBTC": {
        "custody_type": "trust-minimized", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Staking yield",
        "description": "Babylon LST. BANK token on Binance (Nov 2025)",
        "threat_level": "medium", "momentum": "growing",
        "key_risk_to_babylon": "Babylon LST with Binance listing — distribution advantage",
        "funding": "Binance Labs", "audit_status": "partial",
        "strengths": {"btc_holder": "Babylon yield, governance", "custodian": "Binance listing", "defi_protocol": "USD1 stablecoin"},
        "weaknesses": {"btc_holder": "Small TVL, BANK volatile", "custodian": "Unproven", "defi_protocol": "Limited integrations"},
        "sources": {},
    },
    "coreBTC": {
        "custody_type": "trustless", "kyc": False, "self_custodial": False,
        "ltv_max": None, "apr_range": "Variable",
        "description": "Core Chain. Overcollateralized lockers + guardians. Chain TVL from DeFi Llama API",
        "threat_level": "medium", "momentum": "stable",
        "key_risk_to_babylon": "Trustless lockers model is conceptually similar to TBV vaults",
        "funding": "Core Foundation", "audit_status": "partial",
        "strengths": {"btc_holder": "Trustless via overcollateralization", "custodian": "Distributed lockers", "defi_protocol": "EVM compatible"},
        "weaknesses": {"btc_holder": "Smaller ecosystem, complexity", "custodian": "Collateral management", "defi_protocol": "Core-specific"},
        "sources": {},
    },

    # ===== Cluster 4: Infrastructure =====
    "BOB": {
        "custody_type": "trust-minimized", "kyc": False, "self_custodial": True,
        "description": "BitVM-based hybrid L2 (Bitcoin+Ethereum). SolvBTC integrated",
        "threat_level": "medium", "momentum": "growing",
        "key_risk_to_babylon": "BitVM bridge could become preferred infra if TBV doesn't ship first",
        "funding": "$10M seed (Castle Island Ventures, Mar 2024)", "audit_status": "partial",
        "strengths": {"btc_holder": "BitVM verification", "custodian": "Bridge security", "defi_protocol": "EVM+Bitcoin"},
        "weaknesses": {"btc_holder": "BitVM maturing", "custodian": "Integration overhead", "defi_protocol": "Small ecosystem"},
        "sources": {
            "funding": "CoinDesk (Mar 2024): $10M seed led by Castle Island Ventures",
        },
    },
    "BitLayer": {
        "custody_type": "trust-minimized", "kyc": False, "self_custodial": True,
        "description": "Optimistic verification. BitVM bridge with Cardano",
        "threat_level": "low", "momentum": "stable",
        "key_risk_to_babylon": "Early stage, different approach — low overlap",
        "funding": "Undisclosed", "audit_status": "unaudited",
        "strengths": {"btc_holder": "Scalable optimistic", "custodian": "Bridge innovation", "defi_protocol": "Growing L2"},
        "weaknesses": {"btc_holder": "Challenge delays", "custodian": "Unproven", "defi_protocol": "Fragmented"},
        "sources": {},
    },
    "Citrea": {
        "custody_type": "trustless", "kyc": False, "self_custodial": True,
        "description": "ZK rollup on Bitcoin. Chainway Labs",
        "threat_level": "medium", "momentum": "growing",
        "key_risk_to_babylon": "ZK rollup on Bitcoin is strongest verification narrative, competes with BitVM3",
        "funding": "$16.7M total ($2.7M seed + $14M Series A, Founders Fund Oct 2024)", "audit_status": "unaudited",
        "strengths": {"btc_holder": "ZK = strongest verification", "custodian": "No custody", "defi_protocol": "Bitcoin-native"},
        "weaknesses": {"btc_holder": "Pre-production", "custodian": "Not live", "defi_protocol": "No ecosystem"},
        "sources": {
            "funding": "CoinDesk (Feb 2024): $2.7M seed led by Galaxy; CoinDesk (Oct 2024): $14M Series A led by Founders Fund",
        },
    },
    "Mezo": {
        "custody_type": "semi-custodial", "kyc": False, "self_custodial": False,
        "description": "Thesis venture. Bitcoin L2. Proof of HODL. TVL from DeFi Llama API",
        "threat_level": "medium", "momentum": "stable",
        "key_risk_to_babylon": "Thesis-backed, stBTC integration, yield stacking competes with TBV yield",
        "funding": "$21M Series A (Pantera Capital, Apr 2024)", "audit_status": "partial",
        "strengths": {"btc_holder": "Yield stacking", "custodian": "Thesis backing", "defi_protocol": "Curve integration"},
        "weaknesses": {"btc_holder": "Semi-custodial, 2-3% fees", "custodian": "Venture-dependent", "defi_protocol": "Niche L2"},
        "sources": {
            "funding": "CoinDesk / Fortune (Apr 2024): $21M Series A led by Pantera Capital",
        },
    },

    # ===== Babylon TBV (comparison overlay) =====
    "Babylon TBV": {
        "custody_type": "trustless", "kyc": False, "self_custodial": True,
        "ltv_max": None, "apr_range": "TBD — projected competitive with Aave BTC rates",
        "description": "Trustless Bitcoin Vaults. Native BTC via BitVM3/ZK. No wrapping. $5B+ staked via Babylon protocol. Aave V4 spoke (target Apr 2026)",
        "threat_level": "n/a", "momentum": "growing",
        "key_risk_to_babylon": "N/A — this is us",
        "funding": "$15M a16z Crypto (Jan 7, 2026)", "audit_status": "partial",
        "strengths": {"btc_holder": "TRUE self-custody, no wrapping, no KYC, native BTC", "custodian": "Standardized vault integration", "defi_protocol": "Native BTC collateral, Aave V4 spoke"},
        "weaknesses": {"btc_holder": "Pre-launch, BitVM3 complexity", "custodian": "New standard, not battle-tested", "defi_protocol": "No live liquidity yet"},
        "sources": {
            "funding": "CoinDesk (Jan 7, 2026): $15M from a16z Crypto for Trustless BTCVaults; Yahoo Finance confirms",
            "description": "Babylon staking dashboard: $5B+ staked; Aave V4 spoke announcement Dec 2025",
        },
    },
}

TRUST_SCORES = {
    "custodial": 1,
    "non-custodial": 3.5,
    "semi-custodial": 1.5,
    "federated-multisig": 2,
    "trust-minimized": 3,
    "trustless": 4,
}


def get_static_metadata():
    """Return the full metadata dict."""
    return COMPETITOR_METADATA
